---
- name: This playbook uninstall httpd
  hosts: all
  become: true
  tasks:
  - name: stop httpd service
    service:
      name: httpd
      state: stopped
  - name: uninstall apache
    apt:
      name: httpd
      state: removed
